dist: bionic
language: node_js
node_js:
  - 10
  - 12
  - node
env:
  global:
    - COVERALLS_PARALLEL=true
script:
  - yarn lint
  - yarn check
  - yarn test
after_success: yarn run coverage
cache: yarn
notifications:
  webhooks: https://coveralls.io/webhook
